# example_travisci_multi/.travis.yml

language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - rake db:create
  - rake db:migrate
  - rake db:test:prepare

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec